name: Validate Project

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci_validation:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2.2
        bundler-cache: true
        cache-version: 1
  
    - name: Test
      run: bin/rails test
